### ISSUE TITLE
The VPN is returning “Unstable/No signal” message on the removed device after 4 seconds from removal

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#183]
#### Affected versions:
* 1.202011110856;

#### Affected Platforms:
* Linux Ubuntu 20.04;

#### Prerequisites:
* Have the VPN app installed;
* Have a FxA account with active subscription for Mozilla VPN;
* Use the same account to activate VPN client on Windows, Linux and Android;

#### Steps to reproduce:
1. Open the VPN app on all devices using the account from prerequisites;
1. Go to Windows VPN client and remove the Linux VPN client;
1. Observe the VPN app behavior on the removed device (Linux);

#### Expected result:
* User is signed out. A red banner informing the user that it was signed out and the device was removed is displayed.

#### Actual result:
* Nothing happens. If we try to turn on the VPN on Linux, a “Unstable/No Signal” message is displayed after 4-5 seconds;

#### Notes:
* tried the same STR while removing Windows client from and Android, and the device is removed without problems, almost instantly.
* I am using the latest stage build on Windows, the latest cross-plat build on Android and the latest cross-plat build on Linux.
* while the VPN is in that Unstable/No Signal state, the internet is not working on that device.
![nosignal after removal](https://user-images.githubusercontent.com/15685960/98803462-70cbfb80-241d-11eb-9a03-ab345b91f887.gif)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-77)
┆author: Data Sync

**Comment by bakulf** [comment]
@rlr do you have idea about how to make this more predicable?

**Comment by rlr** [comment]
> @rlr do you have idea about how to make this more predicable?

All I can think of is doing an API call right before trying to connect. But that wont fix the issue if the device is already connected.

**Comment by stanleykerr** [comment]
@bakulf I don't know if there's been any progress, but how about counting how many pings fail while unstable? After it reaches a limit, disable the VPN to try to restore regular internet access and check for authorization. If the request fails, the user might still not have internet access. Otherwise, the valid response will tell you if it's still an authorized device.

**Comment by chrismore** [comment]
I am going to bump this down to P2 and have @jess-cook03 look into this issue and see if we can have a solution that is easy to understand from the customer perspective. There are probably multiple ways to handle this technically.

**Comment by ValentinaPC** [comment]
So, if the user ends up in this case, now with the new "confirming" VPN state, the following happens:
- after Linux device is removed=> the VPN app is in "No signal" state after 4 seconds (as mentioned above);
- I turn the VPN off and back on=> the VPN app is in "confirming" state - state that turns into VPN off after aprox 2 minutes and than in - "Authentication failed. Try again!" after few seconds.

**Comment by jess-cook03** [comment]
@bakulf is this issue resolved now based on the issues mentioned above now being closed ?

**Comment by ValentinaPC** [comment]
@bakulf @jess-cook03 This is still happening as mentioned in the above [comment](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/183#issuecomment-756635702).

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Peter Benvenuto Jessica Cook take a look at this again if its something that we need to revisit the UX/UI messaging

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed while using released Mozilla VPN 2.10 (2.10.1) builds.

If the VPN is OFF on the device that gets removed (Prod server), and we try to turn it on, user is signed out and an authentication failure red banner is displayed. (expected)
