### ISSUE TITLE
[iOS] Restore button within subscription page

### ISSUE THREAD

**Issue by jess-cook03** [mozilla-mobile/mozilla-vpn-client#245]
The restore purchase link on iOS doesn't seem to work when or it lags when selected and doesn't seem to bring users to where it needs to go...
![IMG_4894](https://user-images.githubusercontent.com/54991698/99577207-04b33f80-29a9-11eb-8787-e754cd9646de.PNG)
When you click it.... it seems to kinda freeze... I know @bakulf had mentioned this before. I wanted to capture this here as we work through this.

**Comment by jess-cook03** [comment]
@ValentinaPC 
Are we able to test this formally? 
@bakulf cc you here as well .....
The issue occurring was:

- User selects 'restore purchases' within subscription screen

- Subscribe now button then trigger loader/spinner state

- Screen gets stuck or held up in this spinner mode and nothing happens

- There is no interaction behavior when user selects restore purchases --- that is the main concern -- also where does the user land or where are they suppose to land if they select this 'restore option'

![IMG_4899](https://user-images.githubusercontent.com/54991698/99695753-ec502d00-2a5b-11eb-88e2-ae00b80a782a.PNG)

**Comment by ValentinaPC** [comment]
@jess-cook03 Yes, I can check this on a real device, and I did.
Verified this on an iPad with iOS 14.2 while using the version  2.202011201408 of the VPN cross-plat build.
- While clicking on the "Restore purchase" button nothing happens, except the appearance of the spinning wheel for 3-4 seconds on the "Subscribe now" button.
- If, after finalizing the subscription, I click quickly on the "Restore purchase" button, before the TURN ON VPN screen is loaded, a message is displayed.
![image](https://user-images.githubusercontent.com/15685960/99959383-98af4d80-2d93-11eb-972e-1203bdb9e7c5.png)

**Comment by bakulf** [comment]
This should be now fully support. @ValentinaPC can you confirm it?

**Comment by ValentinaPC** [comment]
@bakulf 
While using VPN v. 2.202011301207 and an iPad 14.2 I receive an error while I click on the "Restore purchase" button, and the spinning wheel is still on the "Subscribe now" button.
Attaching the error.
![image](https://user-images.githubusercontent.com/15685960/100866757-cd14bf00-34a1-11eb-8532-b6493ffc2246.png)

**Comment by jess-cook03** [comment]
@bakulf @lesleyjanenorton 
Per our conversation yesterday, wanting to document this UI change -- I would say this would be a nice to have for this release if we can get to it. Backlog for future if not.

[Link to figma spec](https://www.figma.com/file/FhYZu3RiEbCNVLQnZ1q1MS/IAP?node-id=202%3A348)

![308](https://user-images.githubusercontent.com/54991698/100928207-eb83b600-34b3-11eb-9146-532be6545b35.png)

**Comment by chrismore** [comment]
We will keep this a P1. We should do this, but we are right up against code freeze and thus we won't block release, but @lesleyjanenorton will talk to @bakulf to see if we can get this in tomorrow (Friday). This should not be prioritized until other P0s are done.

**Comment by bakulf** [comment]
The new version of IAP uses a big spinner for the subscription and the restore, similarly to what we have for the authentication. Let's close this issue.

**Comment by ValentinaPC** [comment]
Verified this on the latest VPN beta build, using iOS 14.2.
When clicking o the "Restore purchase" the user is redirected to "Confirming subscription" page, page that is close with an error.
Same for "Subscribe now" action.
See bellow video.
![ezgif com-video-to-gif(7)](https://user-images.githubusercontent.com/15685960/101367241-9f1ee880-38ae-11eb-9a4d-f5ce858a6739.gif)

**Comment by chrismore** [comment]
@bakulf while there is a spinner here now, the restore purchases fails and sends the user back to the subscribe now page.

**Comment by bakulf** [comment]
This should be fixed on the server-side. Can this be checked again? @ValentinaPC

**Comment by ValentinaPC** [comment]
Verified this on the latest VPN beta build (2.202012091934), using iOS 14.2.

- When clicking o the "Restore purchase" (without having a subscription for that account) the user is redirected to "Confirming subscription" page, page that is close with the error: "Subscription failed. Try Again!" (expected)
- Same error message is displayed also for **"Subscribe now" action, if it is made after the restore one**.

If we make only the Subscribe now action => subscription is made with success and no error is displayed.

I'll also attach the logs.
[yNfiWJkZ.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/5672227/yNfiWJkZ.txt)

**Comment by chrismore** [comment]
@ValentinaPC are you saying this is verified fixed or verified still a problem? thanks

**Comment by chrismore** [comment]
Not blocking release, but improve the UX in the future. People who subscribe and unsubscribe in a month and then try to first subscribe again is an edge case.

**Comment by ValentinaPC** [comment]
@chrismore you can remove the p1 label, if is not important for this release? Thanks!

**Comment by chrismore** [comment]
@lesleyjanenorton even though we de-prioritized this for the initial v2.0 release, did we keep the button on iOS?

**Comment by chrismore** [comment]
Let's hold on any further changes for this issue until v2.0 iOS is in the hands of customers as we have made changes regarding the restore button already. We will need to re-prioritize and evaluate all issues beyond the P0 issues that were blockers for this first release. Let's close this issue and we'll create a new issue if needed.
