### ISSUE TITLE
While VPN is ON device removal is not made instantly

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#501]
#### Affected versions:
* 2.0.3 build; 

#### Affected Platforms:
* All Linux;

#### Prerequisites:
* Have the VPN app installed;
* Have a FxA account with active subscription for Mozilla VPN;
* Have multiple devices using the VPN;

#### Steps to reproduce:
1. Open the VPN app;
1. Tap to turn ON the VPN;
1. Go to My Devices page;
1. Remove a device;

#### Expected result:
* The device is removed instantly.

#### Actual result:
* Recycle bin for the removed device is replaced by a spinning wheel that stays like that

#### Notes:
* The device is removed if leaving the page.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-96)

**Comment by bakulf** [comment]
This is fixed.

**Comment by ValentinaPC** [comment]
Verified this on Linux Ubuntu 20.04 VPN build 2.3.0 (2.202105190912).
The issue is still reproducing as mentioned in the above STRs.
![image](https://user-images.githubusercontent.com/15685960/118931868-1a9dbf00-b950-11eb-92fe-f9906abd170b.png)

**Comment by bakulf** [comment]
This is now fixed.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified as fixed on the last VPN 2.8 build, on all platforms.

The slowlines of device removal impacts only de 6th device screen.
