### ISSUE TITLE
Segmentation fault with Qt 6.4.1 on Fedora 37

### ISSUE THREAD

**Issue by arnobl** [mozilla-mobile/mozilla-vpn-client#5050]
**Describe the bug**
After the system update that upgraded Qt from 6.3.1-2.fc37.x86_64 to 6.4.1-1.fc37.x86_64, the vpn crashes on start with a:

```
> mozillavpn             
QML debugging is enabled. Only use this in a safe environment.
[1]    8000 segmentation fault (core dumped)  mozillavpn
```

**VPN version:**
2.11.0 (2.202211100718)
Installed from the RPM package Github actions provide.

**Affected Platforms:**
Fedora 37

**Steps to reproduce:**
Start the app

**Expected result:**
Should not crash.

**Actual result:**
Crashes

**Additional notes:**

```
ldd $(which mozillavpn) 
	linux-vdso.so.1 (0x00007ffea1fb8000)
	libQt6Test.so.6 => /lib64/libQt6Test.so.6 (0x00007f768f5e4000)
	libQt6NetworkAuth.so.6 => /lib64/libQt6NetworkAuth.so.6 (0x00007f768ebcb000)
	libQt6DBus.so.6 => /lib64/libQt6DBus.so.6 (0x00007f768eafd000)
	libpolkit-gobject-1.so.0 => /lib64/libpolkit-gobject-1.so.0 (0x00007f768f5c3000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f768ea9c000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f768e95c000)
	libQt6WebSockets.so.6 => /lib64/libQt6WebSockets.so.6 (0x00007f768e928000)
	libQt6Widgets.so.6 => /lib64/libQt6Widgets.so.6 (0x00007f768e000000)
	libQt6Quick.so.6 => /lib64/libQt6Quick.so.6 (0x00007f768d800000)
	libQt6Qml.so.6 => /lib64/libQt6Qml.so.6 (0x00007f768d200000)
	libQt6Network.so.6 => /lib64/libQt6Network.so.6 (0x00007f768d03c000)
	libQt6Gui.so.6 => /lib64/libQt6Gui.so.6 (0x00007f768c600000)
	libQt6Core.so.6 => /lib64/libQt6Core.so.6 (0x00007f768be00000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f768ba00000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f768e846000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f768e826000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f768b823000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f768f66b000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f768e7d1000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007f768b645000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f768df23000)
	libffi.so.8 => /lib64/libffi.so.8 (0x00007f768e7c3000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f768cf9f000)
	libQt6QmlModels.so.6 => /lib64/libQt6QmlModels.so.6 (0x00007f768c52d000)
	libQt6OpenGL.so.6 => /lib64/libQt6OpenGL.so.6 (0x00007f768c484000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f768cf48000)
	libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f768e7b4000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f768d7e6000)
	libEGL.so.1 => /lib64/libEGL.so.1 (0x00007f768d7d4000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f768bdb1000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f768bc6a000)
	libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007f768b5fc000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f768cf16000)
	libOpenGL.so.0 => /lib64/libOpenGL.so.0 (0x00007f768c459000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f768b5c2000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f768b4d6000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f768b408000)
	libicui18n.so.71 => /lib64/libicui18n.so.71 (0x00007f768b000000)
	libicuuc.so.71 => /lib64/libicuuc.so.71 (0x00007f768ae03000)
	libdouble-conversion.so.3 => /lib64/libdouble-conversion.so.3 (0x00007f768d7bf000)
	libb2.so.1 => /lib64/libb2.so.1 (0x00007f768df1a000)
	libpcre2-16.so.0 => /lib64/libpcre2-16.so.0 (0x00007f768b37a000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f768d7b8000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007f768b333000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f768bc3d000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f768d7ae000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f768add8000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f768ad25000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f768ad01000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f768ac24000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f768ac0b000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f768c452000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f768abfa000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f768c44b000)
	libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f768a600000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f768abe7000)
	libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f768abc4000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f768ab0b000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f768a486000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f768aae0000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f768aacb000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f768aaa9000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f768aa96000)
	libicudata.so.71 => /lib64/libicudata.so.71 (0x00007f7688600000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f768aa4c000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f768a44d000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f768bc37000)
```

`sudo journalctl -r --grep=mozillavpn`:

```
 systemd-coredump[9840]: [🡕] Process 9819 (mozillavpn) of user 1000 dumped core.
                                                               
               Module linux-vdso.so.1 with build-id f1344d7d7c9efcbcc6c90cee049c4f55e997d439
               Module libqmldbg_tcp.so with build-id eb55530aedf7332661f5dd66caae1f5c5b07294c
               Metadata for module libqmldbg_tcp.so owned by FDO found: {
                       "type" : "rpm",
                       "name" : "qt6-qtdeclarative",
                       "version" : "6.4.1-1.fc37",
                       "architecture" : "x86_64",
                       "osCpe" : "cpe:/o:fedoraproject:fedora:37"
               }
               
               Module libqmldbg_messages.so with build-id f99aeb055fbaa6fd95abc599ed3e3dc4872fdc23
               Metadata for module libqmldbg_messages.so owned by FDO found: {
                       "type" : "rpm",
                       "name" : "qt6-qtdeclarative",
                       "version" : "6.4.1-1.fc37",
                       "architecture" : "x86_64",
                       "osCpe" : "cpe:/o:fedoraproject:fedora:37"
               }
               
               Module libqmldbg_quickprofiler.so with build-id 83b3901827d02696c0ada8d352b59362d22b8c65
               Metadata for module libqmldbg_quickprofiler.so owned by FDO found: {
                       "type" : "rpm",
                       "name" : "qt6-qtdeclarative",
                       "version" : "6.4.1-1.fc37",
                       "architecture" : "x86_64",
                       "osCpe" : "cpe:/o:fedoraproject:fedora:37"
               }
               
               Module libqmldbg_profiler.so with build-id a478ccaecdb27c8ac31a7bff66e1b69de219bbf0
               Metadata for module libqmldbg_profiler.so owned by FDO found: {
                       "type" : "rpm",
                       "name" : "qt6-qtdeclarative",
                       "version" : "6.4.1-1.fc37",
                       "architecture" : "x86_64",
                       "osCpe" : "cpe:/o:fedoraproject:fedora:37"
               }
               
               Module libqmldbg_debugger.so with build-id 5021f229f29db9ec0c6037d0a68688bbcb0f3bbd
               Metadata for module libqmldbg_debugger.so owned by FDO found: {
                       "type" : "rpm",
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3385)

**Comment by bakulf** [comment]
Can you please share the log file?  ~/.local/share/mozillavpn.txt

**Comment by arnobl** [comment]
```[28.11.2022 08:45:02.548] Debug: (main - LogHandler) Log file: ~/.local/share/mozillavpn.txt
[28.11.2022 08:45:02.548] Debug: (main - Localizer) Loading language:
[28.11.2022 08:45:02.564] Info: (main - CommandUI) MozillaVPN 2.11.0
[28.11.2022 08:45:02.564] Debug: (model - Feature) Initializing feature accountDeletion
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature addon
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature addonSignature
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature appReview
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature benchmarkUpload
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature bundleUpgrade
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature captivePortal
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature customDNS
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature freeTrial
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature inAppAccountCreate
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature inAppAuthentication
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature inAppPurchase
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature keyRegeneration
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature lanAccess
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature mobileOnboarding
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature multiHop
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature notificationControl
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature serverUnavailableNotification
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature shareLogs
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature splitTunnel
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature startOnBoot
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature subscriptionManagement
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature unsecuredNetworkNotification
[28.11.2022 08:45:02.565] Debug: (model - Feature) Initializing feature websocket
[28.11.2022 08:45:02.565] Info: (main - CommandUI) User-Agent: MozillaVPN/2.11.0 (sys:fedora 37)
[28.11.2022 08:45:02.565] Debug: (main - CommandUI) UI starting
[28.11.2022 08:45:02.565] Debug: (main - CommandUI) Maybe start at boot
[28.11.2022 08:45:02.566] Debug: (main - EventListener) Checking other instances
[28.11.2022 08:45:02.566] Warning: (main - EventListener) No other instances found - no unix socket
[28.11.2022 08:45:02.566] Debug: (main - EventListener) event listener created
[28.11.2022 08:45:02.566] Debug: (main - EventListener) Server path: /tmp/mozillavpn.ui.sock
[28.11.2022 08:45:02.579] Debug: (main - CommandUI) Started QML Debugging server on 0.0.0.0:1234
```

The beginning of this file. Each time I tried to launch using the latest qt version I got such a block message.

When I downgraded Qt (it worked again), the next messages are:

```
[28.11.2022 09:06:57.147] Debug: (model - FeedbackCategoryModel) Adding: Bugs/erreurs du produit
[28.11.2022 09:06:57.147] Debug: (model - FeedbackCategoryModel) Adding: Connexion réseau/vitesse
[28.11.2022 09:06:57.147] Debug: (model - FeedbackCategoryModel) Adding: Qualité du produit
[28.11.2022 09:06:57.147] Debug: (model - FeedbackCategoryModel) Adding: Accès au service
[28.11.2022 09:06:57.147] Debug: (model - FeedbackCategoryModel) Adding: Compatibilité
[28.11.2022 09:06:57.147] Debug: (model - FeedbackCategoryModel) Adding: Facilité d’utilisation
[28.11.2022 09:06:57.147] Debug: (model - FeedbackCategoryModel) Adding: Autre
...
```

**Comment by JesseMaurais** [comment]
I have the same issue with 2.13 on F37 with the identical Qt version.

**Comment by SirFunkalot** [comment]
Can confirm this issue. Instructing dnf to downgrade qt6-qtbase.x86_64 permits normal operation of the VPN client.

**Comment by marcel263** [comment]
reproducible 2.13.0 (2.202212251253)

**Comment by redsunsolutions** [comment]
Same here, the UI for the VPN does not display with: 
- Fedora 37
- mozilla-vpn 2.13.0 (2.202212260742)
- qt6 6.4.1-1

Downgrading to:
- qt6 6.3.1-3 
will have the VPN's UI display again.

I just want to say I am a big fan of Mozilla and love that you all made a VPN. 
I am a long time Fedora user.
I truly hope one day, that Mozilla will put out an official version for Fedora. 
There might be more Fedora users out there than Mozilla realizes.

**Comment by JesseMaurais** [comment]
It seems to be purely a binary compatibility issue. I built the latest code with 6.4.1 and it runs fine.

**Comment by artfwo** [comment]
Bumped Fedora version in PR #5433 to use Fedora 37 image for building packages, but not sure if the RPM workflow is going be run against the PR, I think this needs some kind of approval from the maintainers.

**Comment by artfwo** [comment]
Got the packages working at Fedora 37 as of build https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/3850375066 - there are some failing tests, not sure if those happen because of Qt incompatibility, so I'm probably going to look into those later.

**Comment by artfwo** [comment]
With #5433 being merged, this should be fixed for subsequent builds.

**Comment by arnobl** [comment]
This still does not work. Using 2.13 I still have a `[1]    5398 segmentation fault (core dumped)  mozillavpn`


```
[12.02.2023 14:10:25.842] Debug: Loading language:
[12.02.2023 14:10:25.848] Info: MozillaVPN 2.13.0
[12.02.2023 14:10:25.848] Info: User-Agent: MozillaVPN/2.13.0 (sys:fedora 37; iap:true)
[12.02.2023 14:10:25.848] Debug: UI starting
[12.02.2023 14:10:25.848] Debug: Checking other instances
[12.02.2023 14:10:25.848] Debug: Try to communicate with the existing instance
[12.02.2023 14:10:25.848] Error: Connection failed.
[12.02.2023 14:10:25.848] Debug: event listener created
[12.02.2023 14:10:25.848] Debug: Server path: /tmp/mozillavpn.ui.sock
[12.02.2023 14:10:25.853] Debug: Started QML Debugging server on 0.0.0.0:1234
[12.02.2023 14:10:25.855] Debug: Initializing VPNGlean
[12.02.2023 14:10:25.856] Debug: Initializing feature accountDeletion
[12.02.2023 14:10:25.856] Debug: Initializing feature addon
[12.02.2023 14:10:25.856] Debug: Initializing feature addonSignature
[12.02.2023 14:10:25.856] Debug: Initializing feature appReview
[12.02.2023 14:10:25.856] Debug: Initializing feature benchmarkUpload
[12.02.2023 14:10:25.856] Debug: Initializing feature bundleUpgrade
[12.02.2023 14:10:25.856] Debug: Initializing feature captivePortal
[12.02.2023 14:10:25.856] Debug: Initializing feature customDNS
[12.02.2023 14:10:25.856] Debug: Initializing feature freeTrial
[12.02.2023 14:10:25.856] Debug: Initializing feature inAppAccountCreate
[12.02.2023 14:10:25.856] Debug: Initializing feature inAppAuthentication
[12.02.2023 14:10:25.856] Debug: Initializing feature webPurchase
[12.02.2023 14:10:25.856] Debug: Initializing feature keyRegeneration
[12.02.2023 14:10:25.856] Debug: Initializing feature lanAccess
[12.02.2023 14:10:25.856] Debug: Initializing feature mobileOnboarding
[12.02.2023 14:10:25.856] Debug: Initializing feature multiHop
[12.02.2023 14:10:25.856] Debug: Initializing feature notificationControl
[12.02.2023 14:10:25.856] Debug: Initializing feature recommendedServers
[12.02.2023 14:10:25.856] Debug: Initializing feature serverUnavailableNotification
[12.02.2023 14:10:25.856] Debug: Initializing feature serverConnectionScore
[12.02.2023 14:10:25.856] Debug: Initializing feature shareLogs
[12.02.2023 14:10:25.856] Debug: Initializing feature splitTunnel
[12.02.2023 14:10:25.857] Debug: Initializing feature startOnBoot
[12.02.2023 14:10:25.857] Debug: Initializing feature subscriptionManagement
[12.02.2023 14:10:25.857] Debug: Initializing feature unsecuredNetworkNotification
[12.02.2023 14:10:25.857] Debug: Initializing feature websocket
[12.02.2023 14:10:25.857] Debug: Initializing feature gleanRust
[12.02.2023 14:10:25.857] Debug: Initializing feature sentry
[12.02.2023 14:10:25.886] Info: Creating new Glean v52.0.0
```

I still have to:
dnf install qt6-qt5compat-6.3.1-3.fc37.x86_64
dnf versionlock qt6-qtbase-6.3.1-4.fc37

to make the app works.

**Comment by artfwo** [comment]
@arnobl have you tried the main branch? it looks like 2.13 [doesn't have the change](https://github.com/mozilla-mobile/mozilla-vpn-client/commits/releases/2.13.0) and is still being built with fedora 36.
