### ISSUE TITLE
Server switch is not finalized after swipe-kill while VPN is in focus

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#565]
#### Affected versions:
* v. 2.0.3 last build; 

#### Affected Platforms:
* Android 10;
* iOS 14.02;

#### Prerequisites:
* Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
1. Turn ON the VPN;
1. Change location;
1. Minimize the app before changing location is finalized;
1. Swipe-kill the app;
1. Re-open the app;
1. See location;

#### Expected result:
* The switch location from STR 3 is finalized and VPN is ON and working.

#### Actual result:
* The switch location from STR 3 is NOT finalized.

#### Notes:
**- on iOS the switch is finalized after the app swipe-kill, but the _VPN is turned OFF_ when coming back in focus.**

https://user-images.githubusercontent.com/15685960/107338819-aa67dd80-6ac4-11eb-99a5-0c05a553b14e.mp4

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-105)
┆author: Data Sync

**Comment by chrismore** [comment]
@ValentinaPC this only happens if you swipe up and kill before the switch is done, right? Seems like an edge case and the process of switching never finished before going into the background. Background apps on mobile devices are different than how desktop operating systems handle things -- mostly for improved battery utilization. 

@strseb what do you think?

**Comment by strseb** [comment]
Well if the app is swipe killed fast enough before we can send "switch to X command" to our service there is actually not much we can do here, as the OS just stops us from doing anything.

**Comment by ValentinaPC** [comment]
@chrismore yes, only if I swipe-kill the app.

**Comment by chrismore** [comment]
> Well if the app is swipe killed fast enough before we can send "switch to X command" to our service there is actually not much we can do here, as the OS just stops us from doing anything.

Yeah, that's how I see it too. When we go into the background, everything stops, and if a user does it quick enough, there isn't much we can do as execution has halted.

**Comment by ValentinaPC** [comment]
@chrismore one more thing - on iOS the location switch is made while in the background, but, the VPN is not turned back ON. (as I mentioned in the "notes" above)

**Comment by chrismore** [comment]
> @chrismore one more thing - on iOS the location switch is made while in the background, but, the VPN is not turned back ON. (as I mentioned in the "notes" above)

ok, so even though the switch is not made, the VPN is in the "off" state while in the background, right? When this happens, are you able to access the internet and you have your original IP?

**Comment by bakulf** [comment]
We are adding the support of server-switching without disconnecting the VPN, in 1 single command.
So far, we support this feature on linux and windows only. The next platform will be macOS. Then android and iOS. This should fix the issue because there is 1 single step to do, instead of 2.

**Comment by ValentinaPC** [comment]
> ok, so even though the switch is not made, the VPN is in the "off" state while in the background, right? When this happens, are you able to access the internet and you have your original IP?

The switch IS made on iOS, but if the switch is finalized in the background, and we swipe-kill the app, the VPN is not turned on.
VPN not being turned ON -> real IP is displayed, internet is working.

**Comment by ValentinaPC** [comment]
We can remove here the qa_major label, as there is no IP leak issue.
The location switch is not finalized in the background, but the IP displayed in after swipe-kill is of the previous location.

**Comment by rbillings** [comment]
We don't have server switching in one place, after disconnection we reconnect- is diff per client. If the user swipe kills, the second step is not one operation across platforms. Suspect it may be fixed for Android, is a race condition.

**Comment by mbirghan** [comment]
For iOS we landed a patch to do the switch in 1 command. This should fix the issue for iOS.

**Comment by ValentinaPC** [comment]
This is **not fixed** - server switch is not finalized while app not in focus - on Android using the last 2.3 VPN build @rbillings @strseb. 

This is verified as fixed on iOS, using the last 2.3 VPN build - the server switch is finalized after the app swipe-kill and the VPN is turned ON when coming back in focus.

Will reopen the issue for Android platform. Please feel free to close it back, if the Android client cannot be fixed.

**Comment by ValentinaPC** [comment]
What is the status for this regarding 2.4? Thanks!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Valentina Virlics Mind looking to see if this is still the case?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed using latest 2.10 builds on both iOS 15 and Android 10.

Even if the user closes the app before location switch being finalized, while reopening the action is finalized and VPN is on.
